---
title: "Case - Movimento pela Base"
author: "Thais Pereira"
date: "15/03/2022"
output:
  html_document:
    theme: flatly  
    self-contained: true
    toc: true
    toc_float: true
    css:
      - estilo.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=TRUE}

library("tidyverse")
library("ggplot2")
library("readr")
library("readxl")
library("googlesheets4")
library("googledrive")
library("reactable")
library("usethis")



```



```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=TRUE}

microdados_ed_basica_2021 <- read_delim("~/currículos/teste_movimento_pela_base/microdados_ed_basica_2021.csv", 
    delim = ";", escape_double = FALSE, locale = locale(encoding='latin1')) 


dicionario_dados <- read_excel("~/currículos/teste_movimento_pela_base/dicionário_dados_educação_básica.xlsx", skip = 6)

```





```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

dicionario_dados %>% 
  select(`Nome da Variável`, `Descrição da Variável`)

```



```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=TRUE}

  microdados_ed_basica_2021_2 <- microdados_ed_basica_2021 %>%  
  select(NO_UF, NO_MUNICIPIO,CO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_INF, QT_MAT_INF_CRE, QT_MAT_INF_PRE) %>% 
  filter(TP_DEPENDENCIA == 3) %>% 
  filter(NO_UF == "Roraima" |
         NO_UF == "Rondônia" |
         NO_UF == "Tocantins" | 
         NO_UF == "Pará"|
         NO_UF == "Acre" |
         NO_UF == "Amazonas"|
         NO_UF == "Amapá") %>% 
  group_by(CO_MUNICIPIO, NO_MUNICIPIO, TP_DEPENDENCIA, NO_UF) %>%
  summarise(across(c(QT_MAT_INF, QT_MAT_INF_CRE, QT_MAT_INF_PRE), 
                         list(soma=sum), na.rm=TRUE)) %>% 
  ungroup() %>% 
  mutate(TP_DEPENDENCIA = gsub(3,"Municipal", TP_DEPENDENCIA))

```

## 1. Tarefa I - Base de Dados

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}


microdados_ed_basica_2021_2 %>% 
  select(NO_UF, CO_MUNICIPIO, NO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_INF_CRE_soma, QT_MAT_INF_PRE_soma, QT_MAT_INF_soma) %>% 
  reactable(
      defaultPageSize = 5,
      searchable = TRUE,
      outlined = FALSE, 
      showPageInfo = TRUE, 
      showPageSizeOptions = TRUE,
      defaultColDef = colDef(
      align = "center",
      headerStyle = list(background = "#f7f7f8")),
      columns = list(
      NO_UF= colDef("Unidade Federativa", minWidth = 105, align = "center"),
      CO_MUNICIPIO = colDef("Código do Município", minWidth = 120, align = "center"),
      NO_MUNICIPIO = colDef("Nome do Município",  minWidth = 120, align = "center"),
      TP_DEPENDENCIA = colDef("Dependência Administrativa",  minWidth = 120, align = "center"),
      QT_MAT_INF_CRE_soma = colDef("Quantidade de Matrículas em Creches",  minWidth = 120, align = "center"),
      QT_MAT_INF_PRE_soma = colDef("Quantidade de Matrículas em Pré-escolas",  minWidth = 120, align = "center"),
      QT_MAT_INF_soma = colDef("Total de Matrículas na Ed. Infantil",  minWidth = 120, align = "center"), 
      pageSizeOptions = c(5, 10,15,20,25,30), bordered = TRUE, striped = FALSE, highlight = TRUE))

```


```{r}

usethis::use_git()

```
















